var VirtualKeyboardLayoutRussian = {
    lower: [
        [
            {value: '`', text: '`', size: 1, color: 'default'},
            {value: '1', text: '1', size: 1, color: 'default'},
            {value: '2', text: '2', size: 1, color: 'default'},
            {value: '3', text: '3', size: 1, color: 'default'},
            {value: '4', text: '4', size: 1, color: 'default'},
            {value: '5', text: '5', size: 1, color: 'default'},
            {value: '6', text: '6', size: 1, color: 'default'},
            {value: '7', text: '7', size: 1, color: 'default'},
            {value: '8', text: '8', size: 1, color: 'default'},
            {value: '9', text: '9', size: 1, color: 'default'},
            {value: '0', text: '0', size: 1, color: 'default'},
            {value: '-', text: '-', size: 1, color: 'default'},
            {value: '=', text: '=', size: 1, color: 'default'},
            {value: 'backspace', text: 'НАЗАД', size: 2, color: 'control'}
        ],
        [
            {value: 'й', text: 'й', size: 1, color: 'default'},
            {value: 'ц', text: 'ц', size: 1, color: 'default'},
            {value: 'у', text: 'у', size: 1, color: 'default'},
            {value: 'к', text: 'к', size: 1, color: 'default'},
            {value: 'е', text: 'е', size: 1, color: 'default'},
            {value: 'н', text: 'н', size: 1, color: 'default'},
            {value: 'г', text: 'г', size: 1, color: 'default'},
            {value: 'ш', text: 'ш', size: 1, color: 'default'},
            {value: 'щ', text: 'щ', size: 1, color: 'default'},
            {value: 'з', text: 'з', size: 1, color: 'default'},
            {value: 'х', text: 'х', size: 1, color: 'default'},
            {value: 'ъ', text: 'ъ', size: 1, color: 'default'},
            {value: '\\', text: '\\', size: 1, color: 'default'},
            {value: 'clear', text: 'ОЧИСТИТЬ', size: 2, color: 'control'}
        ],
        [
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'ф', text: 'ф', size: 1, color: 'default'},
            {value: 'ы', text: 'ы', size: 1, color: 'default'},
            {value: 'в', text: 'в', size: 1, color: 'default'},
            {value: 'а', text: 'а', size: 1, color: 'default'},
            {value: 'п', text: 'п', size: 1, color: 'default'},
            {value: 'р', text: 'р', size: 1, color: 'default'},
            {value: 'о', text: 'о', size: 1, color: 'default'},
            {value: 'л', text: 'л', size: 1, color: 'default'},
            {value: 'д', text: 'д', size: 1, color: 'default'},
            {value: 'ж', text: 'ж', size: 1, color: 'default'},
            {value: 'э', text: 'э', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'enter', text: 'ВВОД', size: 2, color: 'control'}
        ],
        [
            {value: 'caps', text: '&#8657;', size: 2, color: 'control'},
            {value: 'я', text: 'я', size: 1, color: 'default'},
            {value: 'ч', text: 'ч', size: 1, color: 'default'},
            {value: 'с', text: 'с', size: 1, color: 'default'},
            {value: 'м', text: 'м', size: 1, color: 'default'},
            {value: 'и', text: 'и', size: 1, color: 'default'},
            {value: 'т', text: 'т', size: 1, color: 'default'},
            {value: 'ь', text: 'ь', size: 1, color: 'default'},
            {value: 'б', text: 'б', size: 1, color: 'default'},
            {value: 'ю', text: 'ю', size: 1, color: 'default'},
            {value: '.', text: '.', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'cursor_left', text: '&#8592;', size: 1, color: 'control'},
            {value: 'cursor_right', text: '&#8594;', size: 1, color: 'control'}
        ],
        [
            {value: 'symbols', text: '?123', size: 2, color: 'control'},
            {value: 'lang', text: 'РУС', size: 2, color: 'control'},
            {value: ' ', text: 'ПРОБЕЛ', size: 5, color: 'control'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'cancel', text: 'ОТМЕНА', size: 2, color: 'control'}
        ]
    ],
    upper: [
        [
            {value: '`', text: '`', size: 1, color: 'default'},
            {value: '1', text: '1', size: 1, color: 'default'},
            {value: '2', text: '2', size: 1, color: 'default'},
            {value: '3', text: '3', size: 1, color: 'default'},
            {value: '4', text: '4', size: 1, color: 'default'},
            {value: '5', text: '5', size: 1, color: 'default'},
            {value: '6', text: '6', size: 1, color: 'default'},
            {value: '7', text: '7', size: 1, color: 'default'},
            {value: '8', text: '8', size: 1, color: 'default'},
            {value: '9', text: '9', size: 1, color: 'default'},
            {value: '0', text: '0', size: 1, color: 'default'},
            {value: '-', text: '-', size: 1, color: 'default'},
            {value: '=', text: '=', size: 1, color: 'default'},
            {value: 'backspace', text: 'НАЗАД', size: 2, color: 'control'}
        ],
        [
            {value: 'Й', text: 'Й', size: 1, color: 'default'},
            {value: 'Ц', text: 'Ц', size: 1, color: 'default'},
            {value: 'У', text: 'У', size: 1, color: 'default'},
            {value: 'К', text: 'К', size: 1, color: 'default'},
            {value: 'Е', text: 'Е', size: 1, color: 'default'},
            {value: 'Н', text: 'Н', size: 1, color: 'default'},
            {value: 'Г', text: 'Г', size: 1, color: 'default'},
            {value: 'Ш', text: 'Ш', size: 1, color: 'default'},
            {value: 'Щ', text: 'Щ', size: 1, color: 'default'},
            {value: 'З', text: 'З', size: 1, color: 'default'},
            {value: 'Х', text: 'Х', size: 1, color: 'default'},
            {value: 'Ъ', text: 'Ъ', size: 1, color: 'default'},
            {value: '\\', text: '\\', size: 1, color: 'default'},
            {value: 'clear', text: 'ОЧИСТИТЬ', size: 2, color: 'control'}
        ],
        [
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'Ф', text: 'Ф', size: 1, color: 'default'},
            {value: 'Ы', text: 'Ы', size: 1, color: 'default'},
            {value: 'В', text: 'В', size: 1, color: 'default'},
            {value: 'А', text: 'А', size: 1, color: 'default'},
            {value: 'П', text: 'П', size: 1, color: 'default'},
            {value: 'Р', text: 'Р', size: 1, color: 'default'},
            {value: 'О', text: 'О', size: 1, color: 'default'},
            {value: 'Л', text: 'Л', size: 1, color: 'default'},
            {value: 'Д', text: 'Д', size: 1, color: 'default'},
            {value: 'Ж', text: 'Ж', size: 1, color: 'default'},
            {value: 'Э', text: 'Э', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'enter', text: 'ВВОД', size: 2, color: 'control'}
        ],
        [
            {value: 'caps', text: '&#8659;', size: 2, color: 'control_caps_on'},
            {value: 'Я', text: 'Я', size: 1, color: 'default'},
            {value: 'Ч', text: 'Ч', size: 1, color: 'default'},
            {value: 'С', text: 'С', size: 1, color: 'default'},
            {value: 'М', text: 'М', size: 1, color: 'default'},
            {value: 'И', text: 'И', size: 1, color: 'default'},
            {value: 'Т', text: 'Т', size: 1, color: 'default'},
            {value: 'Ь', text: 'Ь', size: 1, color: 'default'},
            {value: 'Б', text: 'Б', size: 1, color: 'default'},
            {value: 'Ю', text: 'Ю', size: 1, color: 'default'},
            {value: '.', text: '.', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'cursor_left', text: '&#8592;', size: 1, color: 'control'},
            {value: 'cursor_right', text: '&#8594;', size: 1, color: 'control'}
        ],
        [
            {value: 'symbols', text: '?123', size: 2, color: 'control'},
            {value: 'lang', text: 'РУС', size: 2, color: 'control'},
            {value: ' ', text: 'ПРОБЕЛ', size: 5, color: 'control'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'cancel', text: 'ОТМЕНА', size: 2, color: 'control'}
        ]
    ],
    symbols: [
        [
            {value: '`', text: '`', size: 1, color: 'default'},
            {value: '1', text: '1', size: 1, color: 'default'},
            {value: '2', text: '2', size: 1, color: 'default'},
            {value: '3', text: '3', size: 1, color: 'default'},
            {value: '4', text: '4', size: 1, color: 'default'},
            {value: '5', text: '5', size: 1, color: 'default'},
            {value: '6', text: '6', size: 1, color: 'default'},
            {value: '7', text: '7', size: 1, color: 'default'},
            {value: '8', text: '8', size: 1, color: 'default'},
            {value: '9', text: '9', size: 1, color: 'default'},
            {value: '0', text: '0', size: 1, color: 'default'},
            {value: '-', text: '-', size: 1, color: 'default'},
            {value: '=', text: '=', size: 1, color: 'default'},
            {value: 'backspace', text: 'НАЗАД', size: 2, color: 'control'}
        ],
        [
            {value: '', text: '', size: 1, color: 'default'},
            {value: '!', text: '!', size: 1, color: 'default'},
            {value: '?', text: '?', size: 1, color: 'default'},
            {value: '@', text: '@', size: 1, color: 'default'},
            {value: '#', text: '#', size: 1, color: 'default'},
            {value: '$', text: '$', size: 1, color: 'default'},
            {value: '%', text: '%', size: 1, color: 'default'},
            {value: '^', text: '^', size: 1, color: 'default'},
            {value: '&', text: '&', size: 1, color: 'default'},
            {value: '*', text: '*', size: 1, color: 'default'},
            {value: '(', text: '(', size: 1, color: 'default'},
            {value: ')', text: ')', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'clear', text: 'ОЧИСТИТЬ', size: 2, color: 'control'}
        ],
        [
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '_', text: '_', size: 1, color: 'default'},
            {value: '+', text: '+', size: 1, color: 'default'},
            {value: '[', text: '[', size: 1, color: 'default'},
            {value: ']', text: ']', size: 1, color: 'default'},
            {value: '{', text: '{', size: 1, color: 'default'},
            {value: '}', text: '}', size: 1, color: 'default'},
            {value: ';', text: ';', size: 1, color: 'default'},
            {value: ':', text: ':', size: 1, color: 'default'},
            {value: '\'', text: '\'', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'enter', text: 'ВВОД', size: 2, color: 'control'}
        ],
        [
            {value: '', text: '', size: 2, color: 'default'},
            {value: '"', text: '"', size: 1, color: 'default'},
            {value: '\\', text: '\\', size: 1, color: 'default'},
            {value: '|', text: '|', size: 1, color: 'default'},
            {value: ',', text: ',', size: 1, color: 'default'},
            {value: '.', text: '.', size: 1, color: 'default'},
            {value: '/', text: '/', size: 1, color: 'default'},
            {value: '<', text: '<', size: 1, color: 'default'},
            {value: '>', text: '>', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'cursor_left', text: '&#8592;', size: 1, color: 'control'},
            {value: 'cursor_right', text: '&#8594;', size: 1, color: 'control'}
        ],
        [
            {value: 'letters', text: 'абв', size: 2, color: 'control'},
            {value: 'lang', text: 'РУС', size: 2, color: 'control'},
            {value: ' ', text: 'ПРОБЕЛ', size: 5, color: 'control'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'cancel', text: 'ОТМЕНА', size: 2, color: 'control'}
        ]
    ]
};