var VirtualKeyboardLayoutEnglish = {
    lower: [
        [
            {value: '`', text: '`', size: 1, color: 'default'},
            {value: '1', text: '1', size: 1, color: 'default'},
            {value: '2', text: '2', size: 1, color: 'default'},
            {value: '3', text: '3', size: 1, color: 'default'},
            {value: '4', text: '4', size: 1, color: 'default'},
            {value: '5', text: '5', size: 1, color: 'default'},
            {value: '6', text: '6', size: 1, color: 'default'},
            {value: '7', text: '7', size: 1, color: 'default'},
            {value: '8', text: '8', size: 1, color: 'default'},
            {value: '9', text: '9', size: 1, color: 'default'},
            {value: '0', text: '0', size: 1, color: 'default'},
            {value: '-', text: '-', size: 1, color: 'default'},
            {value: '=', text: '=', size: 1, color: 'default'},
            {value: 'backspace', text: 'BACKSPACE', size: 2, color: 'control'}
        ],
        [
            {value: 'q', text: 'q', size: 1, color: 'default'},
            {value: 'w', text: 'w', size: 1, color: 'default'},
            {value: 'e', text: 'e', size: 1, color: 'default'},
            {value: 'r', text: 'r', size: 1, color: 'default'},
            {value: 't', text: 't', size: 1, color: 'default'},
            {value: 'y', text: 'y', size: 1, color: 'default'},
            {value: 'u', text: 'u', size: 1, color: 'default'},
            {value: 'i', text: 'i', size: 1, color: 'default'},
            {value: 'o', text: 'o', size: 1, color: 'default'},
            {value: 'p', text: 'p', size: 1, color: 'default'},
            {value: '[', text: '[', size: 1, color: 'default'},
            {value: ']', text: ']', size: 1, color: 'default'},
            {value: '\\', text: '\\', size: 1, color: 'default'},
            {value: 'clear', text: 'CLEAR ALL', size: 2, color: 'control'}
        ],
        [
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'a', text: 'a', size: 1, color: 'default'},
            {value: 's', text: 's', size: 1, color: 'default'},
            {value: 'd', text: 'd', size: 1, color: 'default'},
            {value: 'f', text: 'f', size: 1, color: 'default'},
            {value: 'g', text: 'g', size: 1, color: 'default'},
            {value: 'h', text: 'h', size: 1, color: 'default'},
            {value: 'j', text: 'j', size: 1, color: 'default'},
            {value: 'k', text: 'k', size: 1, color: 'default'},
            {value: 'l', text: 'l', size: 1, color: 'default'},
            {value: ';', text: ';', size: 1, color: 'default'},
            {value: '\'', text: '\'', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'enter', text: 'ENTER', size: 2, color: 'control'}
        ],
        [
            {value: 'caps', text: '&#8657;', size: 2, color: 'control'},
            {value: 'z', text: 'z', size: 1, color: 'default'},
            {value: 'x', text: 'x', size: 1, color: 'default'},
            {value: 'c', text: 'c', size: 1, color: 'default'},
            {value: 'v', text: 'v', size: 1, color: 'default'},
            {value: 'b', text: 'b', size: 1, color: 'default'},
            {value: 'n', text: 'n', size: 1, color: 'default'},
            {value: 'm', text: 'm', size: 1, color: 'default'},
            {value: ',', text: ',', size: 1, color: 'default'},
            {value: '.', text: '.', size: 1, color: 'default'},
            {value: '/', text: '/', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'cursor_left', text: '&#8592;', size: 1, color: 'control'},
            {value: 'cursor_right', text: '&#8594;', size: 1, color: 'control'}
        ],
        [
            {value: 'symbols', text: '?123', size: 2, color: 'control'},
            {value: 'lang', text: 'ENG', size: 2, color: 'control'},
            {value: ' ', text: 'SPACE', size: 5, color: 'control'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'cancel', text: 'CANCEL', size: 2, color: 'control'}
        ]
    ],
    upper: [
        [
            {value: '`', text: '`', size: 1, color: 'default'},
            {value: '1', text: '1', size: 1, color: 'default'},
            {value: '2', text: '2', size: 1, color: 'default'},
            {value: '3', text: '3', size: 1, color: 'default'},
            {value: '4', text: '4', size: 1, color: 'default'},
            {value: '5', text: '5', size: 1, color: 'default'},
            {value: '6', text: '6', size: 1, color: 'default'},
            {value: '7', text: '7', size: 1, color: 'default'},
            {value: '8', text: '8', size: 1, color: 'default'},
            {value: '9', text: '9', size: 1, color: 'default'},
            {value: '0', text: '0', size: 1, color: 'default'},
            {value: '-', text: '-', size: 1, color: 'default'},
            {value: '=', text: '=', size: 1, color: 'default'},
            {value: 'backspace', text: 'BACKSPACE', size: 2, color: 'control'}
        ],
        [
            {value: 'Q', text: 'Q', size: 1, color: 'default'},
            {value: 'W', text: 'W', size: 1, color: 'default'},
            {value: 'E', text: 'E', size: 1, color: 'default'},
            {value: 'R', text: 'R', size: 1, color: 'default'},
            {value: 'T', text: 'T', size: 1, color: 'default'},
            {value: 'Y', text: 'Y', size: 1, color: 'default'},
            {value: 'U', text: 'U', size: 1, color: 'default'},
            {value: 'I', text: 'I', size: 1, color: 'default'},
            {value: 'O', text: 'O', size: 1, color: 'default'},
            {value: 'P', text: 'P', size: 1, color: 'default'},
            {value: '[', text: '[', size: 1, color: 'default'},
            {value: ']', text: ']', size: 1, color: 'default'},
            {value: '\\', text: '\\', size: 1, color: 'default'},
            {value: 'clear', text: 'CLEAR ALL', size: 2, color: 'control'}
        ],
        [
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'A', text: 'A', size: 1, color: 'default'},
            {value: 'S', text: 'S', size: 1, color: 'default'},
            {value: 'D', text: 'D', size: 1, color: 'default'},
            {value: 'F', text: 'F', size: 1, color: 'default'},
            {value: 'G', text: 'G', size: 1, color: 'default'},
            {value: 'H', text: 'H', size: 1, color: 'default'},
            {value: 'J', text: 'J', size: 1, color: 'default'},
            {value: 'K', text: 'K', size: 1, color: 'default'},
            {value: 'L', text: 'L', size: 1, color: 'default'},
            {value: ';', text: ';', size: 1, color: 'default'},
            {value: '\'', text: '\'', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'enter', text: 'ENTER', size: 2, color: 'control'}
        ],
        [
            {value: 'caps', text: '&#8659;', size: 2, color: 'control_caps_on'},
            {value: 'Z', text: 'Z', size: 1, color: 'default'},
            {value: 'X', text: 'X', size: 1, color: 'default'},
            {value: 'C', text: 'C', size: 1, color: 'default'},
            {value: 'V', text: 'V', size: 1, color: 'default'},
            {value: 'B', text: 'B', size: 1, color: 'default'},
            {value: 'N', text: 'N', size: 1, color: 'default'},
            {value: 'M', text: 'M', size: 1, color: 'default'},
            {value: ',', text: ',', size: 1, color: 'default'},
            {value: '.', text: '.', size: 1, color: 'default'},
            {value: '/', text: '/', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'cursor_left', text: '&#8592;', size: 1, color: 'control'},
            {value: 'cursor_right', text: '&#8594;', size: 1, color: 'control'}
        ],
        [
            {value: 'symbols', text: '?123', size: 2, color: 'control'},
            {value: 'lang', text: 'ENG', size: 2, color: 'control'},
            {value: ' ', text: 'SPACE', size: 5, color: 'control'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'cancel', text: 'CANCEL', size: 2, color: 'control'}
        ]
    ],
    symbols: [
        [
            {value: '`', text: '`', size: 1, color: 'default'},
            {value: '1', text: '1', size: 1, color: 'default'},
            {value: '2', text: '2', size: 1, color: 'default'},
            {value: '3', text: '3', size: 1, color: 'default'},
            {value: '4', text: '4', size: 1, color: 'default'},
            {value: '5', text: '5', size: 1, color: 'default'},
            {value: '6', text: '6', size: 1, color: 'default'},
            {value: '7', text: '7', size: 1, color: 'default'},
            {value: '8', text: '8', size: 1, color: 'default'},
            {value: '9', text: '9', size: 1, color: 'default'},
            {value: '0', text: '0', size: 1, color: 'default'},
            {value: '-', text: '-', size: 1, color: 'default'},
            {value: '=', text: '=', size: 1, color: 'default'},
            {value: 'backspace', text: 'BACKSPACE', size: 2, color: 'control'}
        ],
        [
            {value: '', text: '', size: 1, color: 'default'},
            {value: '!', text: '!', size: 1, color: 'default'},
            {value: '?', text: '?', size: 1, color: 'default'},
            {value: '@', text: '@', size: 1, color: 'default'},
            {value: '#', text: '#', size: 1, color: 'default'},
            {value: '$', text: '$', size: 1, color: 'default'},
            {value: '%', text: '%', size: 1, color: 'default'},
            {value: '^', text: '^', size: 1, color: 'default'},
            {value: '&', text: '&', size: 1, color: 'default'},
            {value: '*', text: '*', size: 1, color: 'default'},
            {value: '(', text: '(', size: 1, color: 'default'},
            {value: ')', text: ')', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'clear', text: 'CLEAR ALL', size: 2, color: 'control'}
        ],
        [
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '_', text: '_', size: 1, color: 'default'},
            {value: '+', text: '+', size: 1, color: 'default'},
            {value: '[', text: '[', size: 1, color: 'default'},
            {value: ']', text: ']', size: 1, color: 'default'},
            {value: '{', text: '{', size: 1, color: 'default'},
            {value: '}', text: '}', size: 1, color: 'default'},
            {value: ';', text: ';', size: 1, color: 'default'},
            {value: ':', text: ':', size: 1, color: 'default'},
            {value: '\'', text: '\'', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'enter', text: 'ENTER', size: 2, color: 'control'}
        ],
        [
            {value: '', text: '', size: 2, color: 'default'},
            {value: '"', text: '"', size: 1, color: 'default'},
            {value: '\\', text: '\\', size: 1, color: 'default'},
            {value: '|', text: '|', size: 1, color: 'default'},
            {value: ',', text: ',', size: 1, color: 'default'},
            {value: '.', text: '.', size: 1, color: 'default'},
            {value: '/', text: '/', size: 1, color: 'default'},
            {value: '<', text: '<', size: 1, color: 'default'},
            {value: '>', text: '>', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'cursor_left', text: '&#8592;', size: 1, color: 'control'},
            {value: 'cursor_right', text: '&#8594;', size: 1, color: 'control'}
        ],
        [
            {value: 'letters', text: 'abc', size: 2, color: 'control'},
            {value: 'lang', text: 'ENG', size: 2, color: 'control'},
            {value: ' ', text: 'SPACE', size: 5, color: 'control'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: '', text: '', size: 1, color: 'default'},
            {value: 'cancel', text: 'CANCEL', size: 2, color: 'control'}
        ]
    ]
};